# Generated by Django 5.2.7 on 2026-04-07 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulancia',
            fields=[
                ('idambulancia', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('BAT', 'Basica Asistencial Terrestre'), ('MAT', 'Medicalizada Asistencial Terrestre'), ('TAB', 'Transporte Asistencial Basico'), ('TAM', 'Transporte Asistencial Medicalizado')], max_length=5)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'ambulancia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('idorganizacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('representante', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'organizacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('idsede', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sede',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RegistroSOAT',
            fields=[
                ('idregistro', models.AutoField(primary_key=True, serialize=False)),
                ('placa_ambulancia', models.CharField(blank=True, max_length=10)),
                ('tipo_ambulancia', models.CharField(blank=True, max_length=50)),
                ('tripulante1', models.CharField(blank=True, max_length=100)),
                ('tripulante2', models.CharField(blank=True, max_length=100)),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('documento_paciente', models.CharField(max_length=30)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cedula de Extranjeria'), ('PA', 'Pasaporte'), ('RC', 'Registro Civil')], default='CC', max_length=3)),
                ('edad_paciente', models.CharField(blank=True, max_length=10)),
                ('genero_paciente', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('direccion_paciente', models.CharField(blank=True, max_length=200)),
                ('telefono_paciente', models.CharField(blank=True, max_length=20)),
                ('fecha_siniestro', models.DateField(blank=True, null=True)),
                ('hora_siniestro', models.TimeField(blank=True, null=True)),
                ('lugar_siniestro', models.CharField(blank=True, max_length=200)),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=50)),
                ('placa_vehiculo', models.CharField(blank=True, max_length=10)),
                ('poliza', models.CharField(blank=True, max_length=50)),
                ('aseguradora', models.CharField(blank=True, max_length=100)),
                ('descripcion_siniestro', models.TextField(blank=True)),
                ('departamento', models.CharField(blank=True, max_length=50)),
                ('ciudad', models.CharField(blank=True, max_length=50)),
                ('sede_prestadora', models.CharField(blank=True, max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ambulancia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ambulancias.ambulancia')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ambulancias.sede')),
            ],
            options={
                'db_table': 'registro_soat',
                'ordering': ['-fecha_registro'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ambulancia',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ambulancias.sede'),
        ),
    ]
